# netlify.toml
[[redirects]]
  from = "/api/*"
  to = "http://54.180.105.38:8080/:splat"
  status = 200
  force = true

# SockJS / STOMP WebSocket 프록시
[[redirects]]
  from = "/ws"
  to = "http://54.180.105.38:8080/ws"
  status = 200
  force = true
