spring:
  datasource:
    url: jdbc:oracle:thin:@//oraclerds.clm48msi0w8m.apnortheast-2.rds.amazonaws.com:1521/ORCL
    username: admin
    password: oraclerds
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
    show-sql: true